### ISSUE TITLE
Incomplete Array Example

### ISSUE THREAD

**Issue by replacem3nts** [learn-co-curriculum/programming-univbasics-4-array-concept-review#4]
In the "Array Vocabulary and Distinguishing Features" lesson, there's an example that invites the student to code along in the IRB to introduce arrays. The codealong has the IRB to print array (Shark Family) that has not been previously entered into the IRB. Asking the IRB to print an array that doesn't exist will return an error message and could cause confusion. 
<img width="1091" alt="Screen Shot 2020-02-09 at 2 26 15 PM" src="https://user-images.githubusercontent.com/57644669/74108431-6d32dd80-4b48-11ea-91f9-427b7b6fd661.png">

**Comment by maxwellbenton** [comment]
Hi @replacem3nts,

Thank you for this feedback. We've updated this lesson to include an additional code snippet for creating the `SHARK_FAMILY` variable, which should resolve this issue.

Thank you for contributing!
